### ISSUE TITLE
ConfigCat OpenSource Community Article - Need your input

### ISSUE THREAD

**Issue by codedbychavez** [Pod-Point/laravel-configcat#10]
Hi @clemblanco 

I’m a Technical Author at ConfigCat writing an article about the growing community of ConfigCat and I would love to get your input to deliver a comprehensive piece.

You’ve worked on this open-source ConfigCat SDK for Laravel.

I would like to get your thoughts on the following topics:

1.  Your background
2.  Your motivation for creating this SDK
3.  And the goal you were trying to accomplish when doing so

    
Feel free to reply to this issue with your answers.

Thank you so much and I'm looking forward to hearing from you.

Kindest regards.

**Comment by clemblanco** [comment]
Hey @codedbychavez I'll close that issue as I believe I got back to you directly by email back in May.

Give me shout if you need anything else! ✌️
